version: '3'
services:
  
  webserver_imr:
    container_name: webserver_imr
    build:
      context: ../build/httpd
      dockerfile: dev.dockerfile
    ports:
      - 4301:80
    volumes:
      - /webroot/imr:/var/www/html:ro
    restart: always
