version: '3'
services: 
  nginx:
    build:
      context: ../build/nginx/web
      dockerfile: Dockerfile
    restart: always
    container_name: webserver-imr-nginx
    ports:
      - 4301:80
    volumes:
      - /webroot/imr:/var/www/html:ro
    links:
      - php-fpm

  php-fpm:
    build:
      context: ../build/nginx/php-fpm
      dockerfile: Dockerfile
    restart: always
    container_name: webserver-imr-php-fpm
    volumes:
      - /webroot/imr:/var/www/html:ro