version: '2'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=vpsloic.loicbertrand.net
      - SUBDOMAINS=webmin,portainer,pgadmin,imr-app,omnidb,
      - VALIDATION=http
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=true #optional
    volumes:
      - ./config:/config
    network_mode: host
    ports:
      - 443:443
      - 80:80
    restart: always
