version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9009:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../appdata/portainer/data:/data
    restart: always
