version: '3'
services:
  mongo:
    build:
      context: ./build
      dockerfile: Dockerfile
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/db/data
